phparkitect/arkitect

README.md
src/CLI/Check.php
tests/E2E/CliTest.php
tests/E2E/phparkitect.php

In this PR I have changed the option `configFile` from `required` to `optional` because the command now is shorter.
If the `configFile` parameter is not sent, `phparkitect` searches automatically in the root of the project the default file configuration called `phparkitect.php`
What do you think?

configFile option optional, not required

---

bin-stub/phparkitect

Senza questa cosa non funziona nei progetti "veri". Errore visto con @AlessandroMinoccheri venerdì.

Fix in bin stub

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

The bug was inside `FileVisitor` because we added dependencies after adding interfaces in a wrong way  like this:
`\Foo\Bar\Baz`
The correct way is already inside `addInterfaces`:
`Foo\Bar\Baz`
Issue related: #135

fixed bug about dependencies

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

In this PR I added the possibility to get dependencies when they are passed as parameters inside functions.
I think that class FileVisitorTest will be too big in the future, but at the moment I don't have other solutions and for the moment could be good enough.
I have escaped scalar values like `int` or `string`

get dependencies when passed as params

---

.php-cs-fixer.dist.php
src/Analyzer/FileParser.php
tests/Unit/Analyzer/FileVisitorTest.php

In this PR I removed the PHP version fixed for the emulator, and now we are using the PHP version dynamically.
Removing PHP version specification break all the tests.
Related issue: #160

fix parsing arrow function using php_version dynamically into parser

---

tests/E2E/Cli/CheckCommandTest.php

I think that these output tests can be replaced with others but at the moment we can solve removing line brakes when we try to compare the output.
Fixing #184

removed line breaks when we try to compare the output

---

src/ClassSet.php
src/Rules/ParsingErrors.php
src/Rules/Violations.php
tests/Unit/Rules/RuleCheckerTest.php

Hello, 
Thanks for this useful project :+1: 
Just a little contribution to avoid deprecation notices on php 8.1:
```
PHPArkitect 0.2.6
Config file: tests/phparkitect.php
Deprecated: Return type of Arkitect\ClassSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/phparkitect/phparkitect/src/ClassSet.php on line 39
Deprecated: Return type of Arkitect\Rules\Violations::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/phparkitect/phparkitect/src/Rules/Violations.php on line 34
Deprecated: …
```

Add return typehint to getIterator methods for php 8.1

---

src/Expression/ForClasses/Extend.php
src/Expression/ForClasses/NotExtend.php
src/Expression/ForClasses/NotHaveDependencyOutsideNamespace.php
tests/Unit/Expressions/ForClasses/NotHaveDependencyOutsideNamespaceTest.php

In this PR I have added a second parameter to this expression `NotHaveDependencyOutsideNamespace`

Adding excluding dependencies as parameters

---

src/Expression/ForClasses/DependsOnlyOnTheseNamespaces.php
tests/Unit/Analyzer/FileVisitorTest.php
tests/Unit/Expressions/ForClasses/DependsOnlyOnTheseNamespacesTest.php

With this PR we are saying that using `DependsOnlyOnTheseNamespaces` is implicit that the same namespace of the parsed class is allowed without specifying it.
Solving #200

added default namespace into depende only on these namespaces expression

---

.github/workflows/build-phar.yml

I changed the PHP version from `7.4` to `7.1` to solve this issue: #242 
In my opinion, this can create future problems, I don't know at the moment if the option `target-php-version` is enough or we have to create a phar version for each PHP version.

changed php version during phar creation

---

src/CLI/Check.php

In this PR I added an `ini_set` to solve the problem about xdebug infinite loop because with big classes with many dependencies this could happen.
This PR solves the issue #251

increase xdebug max nesting level to 10000

---

README.md
src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileVisitor.php
src/Expression/ForClasses/HaveAttribute.php
tests/E2E/PHPUnit/CheckClassHaveAttributeTest.php
tests/E2E/_fixtures/mvc/Controller/BaseController.php
tests/E2E/_fixtures/mvc/Controller/CatalogController.php
tests/E2E/_fixtures/mvc/Controller/Foo.php
tests/E2E/_fixtures/mvc/Controller/ProductsController.php
tests/E2E/_fixtures/mvc/Controller/UserController.php
tests/E2E/_fixtures/mvc/Controller/YieldController.php
tests/E2E/_fixtures/mvc/Model/Catalog.php
tests/E2E/_fixtures/mvc/Model/Products.php
tests/E2E/_fixtures/mvc/Model/User.php
tests/Unit/Analyzer/ClassDescriptionBuilderTest.php
tests/Unit/Analyzer/ClassDescriptionTest.php
tests/Unit/Analyzer/FileVisitorTest.php

Hi there!
This change will add the ability to check for the existence of an attribute on a class. The addition of this ability won't break existing functionality on PHP < 8.0, but because attributes only exist on PHP >= 8.0, using this new expression does require the latter. Perhaps this limitation should be documented explicitly if you are willing to accept the change.
Thanks!

feat: Add `HaveAttribute` class expression

---

src/Analyzer/FileVisitor.php
src/CLI/Runner.php
src/Rules/ArchRule.php
src/Rules/Constraints.php
tests/Unit/Analyzer/FileVisitorTest.php

Parsing enum file

---

README.md
src/RuleBuilders/Architecture/Architecture.php
src/RuleBuilders/Architecture/ShouldOnlyDependOnComponents.php
src/RuleBuilders/Architecture/Where.php
tests/Unit/Architecture/ArchitectureTest.php

In this PR I added the possibility to filter components with `shouldOnlyDependOnComponents` function that generates a rule: `DependsOnlyOnTheseNamespaces`
This can fix some problems about issue #277

added add-shouldOnlyDependOnComponents

---

src/CLI/Version.php

There was an error in showing the version number when phparkitect is installed via composer.
You can reproduce the bug running https://github.com/phparkitect/arkitect-demo .
Now it should work in all cases.

fix bug when a wrong composer.json was used to read the version number

---

README.md
psalm.xml
src/CLI/Command/DebugExpression.php
src/CLI/PhpArkitectApplication.php
tests/E2E/Cli/DebugExpressionCommandTest.php

This should fix #290 
There are some little things to fix, but the core of the functionality should be here...

debug:expression command

---

src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/ClassDescriptionBuilderTest.php
tests/Unit/Analyzer/ClassDescriptionTest.php
tests/Unit/Analyzer/FileVisitorTest.php
tests/Unit/Expressions/ForClasses/DocBlockContainsTest.php
tests/Unit/Expressions/ForClasses/DocBlockNotContainsTest.php
tests/Unit/Expressions/ForClasses/HaveAttributeTest.php

This should fix this issue #301 
Is it a BC?

added parsing and checking functions docblocks

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

Just as with classes, PHPArkitect should handle attributes for enums as well, not resulting in a violation when attributes are present in the enum.
More information in the issue https://github.com/phparkitect/arkitect/issues/306

Handle attributes on enums (PHP8.1)

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

This fix the bug reported by @mmenozi on issue (#308) about scalar types in typed properties. With this fix scalar types will be not detected as dependencies.

Fix bug with typed properties and scalar types (#308)

---

composer.json
src/Analyzer/FileParser.php
src/Analyzer/FileParserFactory.php
src/Analyzer/FileVisitor.php
src/Analyzer/NameResolver.php
tests/Unit/Analyzer/FileParserTest.php
tests/Unit/Analyzer/FileVisitorTest.php

This PR can fix the second docblock problems explained in this issue: #307 about @var --> Not detected

parsing property type into docblocks

---

README.md
src/CLI/Command/Check.php
src/Rules/Violation.php
src/Rules/Violations.php
tests/E2E/Cli/CheckCommandTest.php

If there are a lot of violations in your codebase and you can't at the moment fix them, 
you can use the baseline feature to instruct the tool to ignore past violations.
To create a baseline file, run the `check` command with the `set-baseline` parameter as follows:
```
phparkitect check --set-baseline=my-baseline.json
```
It will produce a json file with the current list of violations.  
To instruct the tool to use the baseline file, run the `check` command with the `use-baseline` parameter as follows:
```
phparkitect check --use-baseline=my-baseline.json
```

Add baseline feature

---

src/Analyzer/NameResolver.php
tests/Unit/Analyzer/FileVisitorTest.php

This PR should solve problem 1 of this issue #307 about aliases

Parsing aliases in docblocks also

---

src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileVisitor.php
src/Expression/ForClasses/Implement.php
src/Expression/ForClasses/NotImplement.php
tests/E2E/Cli/DebugExpressionCommandTest.php
tests/Unit/Analyzer/ClassDescriptionBuilderTest.php
tests/Unit/Analyzer/FileVisitorTest.php
tests/Unit/Expressions/ForClasses/ContainDocBlockLikeTest.php
tests/Unit/Expressions/ForClasses/ExtendTest.php
tests/Unit/Expressions/ForClasses/HaveAttributeTest.php
tests/Unit/Expressions/ForClasses/ImplementTest.php
tests/Unit/Expressions/ForClasses/IsAbstractTest.php
tests/Unit/Expressions/ForClasses/IsFinalTest.php
tests/Unit/Expressions/ForClasses/IsNotAbstractTest.php
tests/Unit/Expressions/ForClasses/IsNotFinalTest.php
tests/Unit/Expressions/ForClasses/NotContainDocBlockLikeTest.php
tests/Unit/Expressions/ForClasses/NotExtendTest.php
tests/Unit/Expressions/ForClasses/NotHaveDependencyOutsideNamespaceTest.php
tests/Unit/Expressions/ForClasses/NotImplementTest.php

This should solve #334 
I added to the `ClassDescription` the property `interface` to understand if the file is an interface or not.
I added to the `FileVisitor` two things that are missing now:
* parsing interfaces
* parsing return types
In another PR we can refactor a little bit the `ClassDescription` adding some default to properties like `interface` to avoid building the class with a lot of mandatory arguments.

Parsing interfaces and return types

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php
tests/Unit/Analyzer/FullyQualifiedClassNameTest.php

This PR should solve #341 
The problem is that: when we get the return type dependencies the string from `$returnType->toCodeString()` (Line 190 FileVisitor.php) starts with a backslash.
The other dependencies are not starting with the backslash, so to standardize our dependencies strings, I decided to remove the first character from the dependencies string if it is a backslash.

removed first character from dependencies string if is a backslash

---

README.md
src/Analyzer/FileParserFactory.php
src/Analyzer/NameResolver.php
src/CLI/Config.php
src/CLI/Runner.php
tests/Unit/Analyzer/FileVisitorTest.php
tests/Unit/CLI/ConfigTest.php

This PR implements the feature described in this issue: https://github.com/phparkitect/arkitect/issues/336
To skip the check you need to add this configuration: 
```
return static function (Config $config): void {
$config->setParseDocBlockCustomTags(false);
//...
}
```
No breaking change is added: if the configuration is not modified the default behavior is used (ParseDocBlockCustomTags=true).

Add a configuration to skip DocBlock Custom Tag detection (#336)

---

src/Rules/Violation.php
src/Rules/Violations.php
tests/Unit/Rules/ViolationsTest.php

On a PHP 7.4 project, after define a baseline, if a violation occurs, all violations are showed, the new violations and the violations defined in the baseline instead to show only new violations.

Fix remove violations from baseline

---

src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileParserFactory.php
src/Analyzer/FullyQualifiedClassName.php
src/Analyzer/PatternString.php
tests/Unit/Analyzer/ClassDescriptionBuilderTest.php
tests/Unit/Analyzer/ClassDescriptionTest.php
tests/Unit/Analyzer/FullyQualifiedClassNameTest.php
tests/Unit/Analyzer/PatternStringTest.php
tests/Unit/Rules/ConstraintsTest.php

We thought to permits only unix shell wildcard for defining namespaces.
In the PR #188 we accidentally added the support for some regexes.
With the PR #327 we made the check a little bit more strict, to avoid bug with partial name matching, but broke the support for some regexes #329 .
We have 3 options:
1 - support both regex and unix wildcard in the same method (this PR fix the problem that we saw now, but I fear there will be a lot more problems in the future)
2 - support only unix wildcard and remove the support for regexes
3 - remove the support for unix wildcard and make a major version that uses only regexes
@micheleorselli @AlessandroMinoccheri what do you think?
I am thinking about solution 2...

Restore support in regex for namespaces and path

---

src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileVisitor.php
src/Analyzer/FullyQualifiedClassName.php
src/Exceptions/InvalidPatternException.php
src/Expression/ForClasses/Extend.php
tests/Unit/Analyzer/ClassDescriptionBuilderTest.php
tests/Unit/Analyzer/ClassDescriptionTest.php
tests/Unit/Expressions/ForClasses/DependsOnlyOnTheseNamespacesTest.php
tests/Unit/Expressions/ForClasses/ExtendTest.php
tests/Unit/Expressions/ForClasses/HaveNameMatchingTest.php
tests/Unit/Expressions/ForClasses/NotDependsOnTheseNamespacesTest.php
tests/Unit/Expressions/ForClasses/NotHaveNameMatchingTest.php
tests/Unit/Expressions/ForClasses/NotResideInTheseNamespacesTest.php
tests/Unit/Expressions/ForClasses/ResideInOneOfTheseNamespacesTest.php
tests/Unit/Rules/ConstraintsTest.php
tests/Unit/Rules/RuleCheckerTest.php
tests/Unit/Rules/SpecsTest.php

I added the error message as an exception.
The message is not perfectly aligned, but I don't know how to improve this cleanly.
I took the opportunity to do some other little refactorings:
- the ClassDescriptionBuilder now is more a builder
- the Extends Rule now supports wildcard in the argument
- I simplified the Rule tests a lot.. I think we could use the same pattern in the other unit tests of rules

Add error message for regex

---

src/CLI/Command/Check.php
src/Rules/Violation.php
src/Rules/Violations.php
tests/E2E/Cli/CheckCommandTest.php
tests/E2E/Smoke/RunArkitectBinTest.php
tests/Unit/Rules/ViolationsTest.php

in our project, we noticed that the order of entries when generating the baseline varies randomly. 
this changes it to sort all entries in the baseline, making it possible to see what the actual changes in the baseline are.

sort violations to avoid unnecessary diffs in the baseline

---

README.md
src/CLI/Command/Check.php
src/Rules/Violations.php
tests/Unit/Rules/ViolationsTest.php

in addition to #364, this PR adds a flag that allows to ignore line number changes completely. (note that the commit from #364 is also contained in this branch)
when using the flag, the line numbers in the baseline might drift out of sync with reality (but the report uses the line numbers from the actual code). we could potentially not store line numbers in the baseline when the flag is active and instead store that line numbers are ignored, so that the flag is only needed when generating the baseline but not when checking with such a baseline.
there is a drawback when the flag is used: if a specific class has a specific violation, new lines that do the same violation will not be detected anymore, because the ignore is globally.
if we would store the count of a specific violation in the …

flag to ignore line numbers

---

src/Expression/ForClasses/IsFinal.php
tests/Unit/Expressions/ForClasses/IsFinalTest.php

Fixed `\Arkitect\Expression\ForClasses\IsFinal` because:
- Traits can not be final

Fixed "IsFinal" for Traits

---

src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileVisitor.php
src/Expression/ForClasses/IsFinal.php
tests/Unit/Analyzer/FileVisitorTest.php
tests/Unit/Expressions/ForClasses/ContainDocBlockLikeTest.php
tests/Unit/Expressions/ForClasses/ExtendTest.php
tests/Unit/Expressions/ForClasses/HaveAttributeTest.php
tests/Unit/Expressions/ForClasses/ImplementTest.php
tests/Unit/Expressions/ForClasses/IsAbstractTest.php
tests/Unit/Expressions/ForClasses/IsFinalTest.php
tests/Unit/Expressions/ForClasses/IsNotAbstractTest.php
tests/Unit/Expressions/ForClasses/IsNotFinalTest.php
tests/Unit/Expressions/ForClasses/NotContainDocBlockLikeTest.php
tests/Unit/Expressions/ForClasses/NotExtendTest.php
tests/Unit/Expressions/ForClasses/NotHaveDependencyOutsideNamespaceTest.php
tests/Unit/Expressions/ForClasses/NotImplementTest.php

Fixed `\Arkitect\Expression\ForClasses\IsFinal` along with various `Arkitect\Analyzer`-classes because:
- Traits can not be final

Fixed "IsFinal" for Enums

---

README.md
src/Expression/ForClasses/IsEnum.php
src/Expression/ForClasses/IsNotEnum.php
tests/Unit/Expressions/ForClasses/IsEnumTest.php
tests/Unit/Expressions/ForClasses/IsNotEnumTest.php

---
name: 🎉 Implements IsEnum && IsNotEnum
about: Test if some classes are enum (or not)
---
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no
| Issue       | Close #...
Allows to tests if some "classes" in a given namespace are enums

Add IsEnum && IsNotEnum expressions

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

An anonymous class declared inside a normal class makes the parser take the `extends` from the anonymous class, instead of the correct one.
```
<?php
namespace Root\Animals;
class Animal
{
}
class Cat extends Animal
{
public function methodWithAnonymous(): void
{
$obj = new class extends \stdClass {};
}
}
```
This code above takes `stdClass` instead of the expected `Animal`.

Bug: Anonymous class extends is parsed instead of class extends

---

README.md

This PR fix an error in the README file. In the README the class `NotResideInOneOfTheseNamespaces` does not exist. The correct one is `NotResideInTheseNamespaces`.

Fix documentation about class NotResideInTheseNamespaces

---

src/Analyzer/NameResolver.php

I initially just ran `php-cs-fixer` to address this however that resulted in inconsistent references within the file, so I've gone with manually fixing it to the most consistent usages, long format for `Use_` and short format for `Name`.

Fix reference consistency in `NameResolver` to resolve CI issues

---

src/CLI/Command/DebugExpression.php
src/CLI/Command/Init.php

Fixes #419 
Aligns with `Check` command which does:
```php
public function __construct()
{
parent::__construct('check');
}
```

Fix fatal error on startup with Symfony 7.x due to changes in command naming

---

README.md
src/Analyzer/FileParser.php
src/Analyzer/NameResolver.php
src/Expression/ForClasses/NotHaveDependencyOutsideNamespace.php
src/Rules/Violation.php
tests/E2E/Cli/CheckCommandTest.php
tests/Unit/Expressions/ForClasses/NotHaveDependencyOutsideNamespaceTest.php

https://github.com/phparkitect/arkitect/issues/338

Add exclude root

---

src/Rules/Violations.php
tests/E2E/Cli/CheckCommandTest.php
tests/E2E/_fixtures/configIgnoreBaselineLineNumbers.php
tests/E2E/_fixtures/line_numbers/Application/Foo.php
tests/E2E/_fixtures/line_numbers/baseline.json
tests/Unit/Rules/ViolationsTest.php

Handles unordered baseline violations when ignoring baseline numbers.
This resolves #428.

Fix handling unordered baseline violations with ignore line numbers option

---

README.md
src/Expression/ForClasses/Extend.php
src/Expression/ForClasses/NotExtend.php
tests/E2E/Cli/DebugExpressionCommandTest.php
tests/Unit/Expressions/ForClasses/ExtendTest.php
tests/Unit/Expressions/ForClasses/NotExtendTest.php

This PR adds the ability to add multiple parameters in the `Extends` constructor. The violation will happen when none of the given strings will match the extend.
In my project I want to check if unit tests extends PHPUnit's TestCase or Mockery's TestCase:
```php
return static function (Config $config): void {
$testClassSet = ClassSet::fromDir(__DIR__ . '/Tests');
$rule = Rule::allClasses()
->that(new ResideInOneOfTheseNamespaces('Tests\Unit'))
->andThat(new HaveNameMatching('*Test'))
->should(new Extend(\PHPUnit\Framework\TestCase::class, \Mockery\Adapter\Phpunit\MockeryTestCase::class))
->because('unit tests must extend the PHPUnit TestCase or Mockery TestCase');
$config->add($testClassSet, $rule);
};
```
When one parameter is used in the `Extend` constructor, it works the same as …

Add ability to check for multiple extends

---

.github/workflows/build.yml
Makefile
composer.json
src/Analyzer/FileParser.php
src/Analyzer/NameResolver.php
src/CLI/TargetPhpVersion.php
tests/Unit/Analyzer/FileVisitorTest.php

* added php 8.4 to the build matrix
* do static checks only on php 7.4 to avoid random results
* upgraded PHP Parser to version 5 to be able to parse php 8.4 code
* added a test to verify php 8.4 can be parsed
* updated our custom NameResolver (ugly, we should find a way to avoid that 😅)

Support php 8.4

---

src/Analyzer/FileVisitor.php
tests/E2E/PHPUnit/CheckAttributeDependencyTest.php
tests/E2E/_fixtures/attributes/Foo.php
tests/E2E/_fixtures/attributes/Invalid/Attr.php
tests/E2E/_fixtures/attributes/Valid/Attr.php
tests/E2E/_fixtures/parse_error/Services/CartService.php

At the moment imports of Attributes are ignored. This results in unreliable results. 
I've adjusted the code to take imports from attributes into account.

fix: Add consideration of Node\Attribute to FileVisitor

---

src/Analyzer/FileVisitor.php
tests/E2E/Cli/CheckCommandTest.php
tests/E2E/_fixtures/DependenciesLeak/FirstModule/Router.php
tests/E2E/_fixtures/DependenciesLeak/FirstModule/routes.php
tests/E2E/_fixtures/DependenciesLeak/SecondModule/SomeClass.php
tests/E2E/_fixtures/configDependenciesLeak.php

This is a failing test for https://github.com/phparkitect/arkitect/issues/389, please see it for more details.

Bug: dependencies leak between files

---

src/Analyzer/FileVisitor.php
src/Expression/ForClasses/Implement.php
src/Expression/ForClasses/NotImplement.php
tests/Integration/ExtendsThrowableTest.php
tests/Integration/ImplementsTest.php
tests/Unit/Analyzer/FileVisitorTest.php

This should provide a fix for #393

Fixes implements and extends rules behaviour

---

tests/Unit/Expressions/ForClasses/ContainDocBlockLikeTest.php
tests/Unit/Expressions/ForClasses/DependsOnlyOnTheseNamespacesTest.php
tests/Unit/Expressions/ForClasses/ExtendTest.php
tests/Unit/Expressions/ForClasses/HaveAttributeTest.php
tests/Unit/Expressions/ForClasses/HaveNameMatchingTest.php
tests/Unit/Expressions/ForClasses/ImplementTest.php
tests/Unit/Expressions/ForClasses/IsAbstractTest.php
tests/Unit/Expressions/ForClasses/IsEnumTest.php
tests/Unit/Expressions/ForClasses/IsFinalTest.php
tests/Unit/Expressions/ForClasses/IsInterfaceTest.php
tests/Unit/Expressions/ForClasses/IsNotAbstractTest.php
tests/Unit/Expressions/ForClasses/IsNotEnumTest.php
tests/Unit/Expressions/ForClasses/IsNotFinalTest.php
tests/Unit/Expressions/ForClasses/IsNotInterfaceTest.php
tests/Unit/Expressions/ForClasses/IsNotReadonlyTest.php
tests/Unit/Expressions/ForClasses/IsNotTraitTest.php
tests/Unit/Expressions/ForClasses/IsReadonlyTest.php
tests/Unit/Expressions/ForClasses/IsTraitTest.php
tests/Unit/Expressions/ForClasses/MatchOneOfTheseNamesTest.php
tests/Unit/Expressions/ForClasses/NotContainDocBlockLikeTest.php
tests/Unit/Expressions/ForClasses/NotDependsOnTheseNamespacesTest.php
tests/Unit/Expressions/ForClasses/NotExtendTest.php
tests/Unit/Expressions/ForClasses/NotHaveDependencyOutsideNamespaceTest.php
tests/Unit/Expressions/ForClasses/NotHaveNameMatchingTest.php
tests/Unit/Expressions/ForClasses/NotImplementTest.php
tests/Unit/Expressions/ForClasses/NotResideInTheseNamespacesTest.php

Using the builder is more coincise and readable and allows to evolve ClassDescription constructor without changing tests

Refactor tests to use ClassDescriptionBuilder instead of new ClassDescription 

---

README.md
src/CLI/Progress/DebugProgress.php
src/CLI/Progress/ProgressBarProgress.php
src/ClassSet.php
tests/Unit/CLI/Progress/DebugProgressTest.php
tests/Unit/ClassSetTest.php

Currently, if we want to include two folders from the project root, we need to add the root of the project and then exclude everything we dont want to include, and remember to add a folder to the config if we add a new folder to the project root.
With the `MultipleDirClassSet` we can specify just the directories we want it to scan,
removing all cruft from our config.

Multiple dirs class set

---

src/Analyzer/PatternString.php
src/Expression/ForClasses/ResideInOneOfTheseNamespaces.php
tests/Unit/Analyzer/PatternStringTest.php

At some point this was correct and then changed into a bug.
I am reverting the change that introduced the bug.

Fix pattern match

---

tests/Unit/Analyzer/PatternStringTest.php

This adds a test case in the PatternStringTest, just to ensure the regression mentioned here #391 is fixed

Adds a test case in PatternStringTest

---

src/CLI/Runner.php
src/Rules/Violation.php
src/Rules/Violations.php

Moved the logic which manage the param `$stopOnFailure` in the `Runner` class

Removes $stopOnFailure params from Violations class

---

composer.json
src/CLI/Command/Check.php
src/CLI/Printer/GitlabPrinter.php
src/CLI/Printer/Printer.php
src/CLI/Printer/PrinterFactory.php
tests/E2E/Cli/CheckCommandTest.php
tests/Unit/CLI/Printer/GitlabPrinterTest.php
tests/Unit/CLI/Printer/JsonPrinterTest.php
tests/Unit/CLI/Printer/PrinterFactoryTest.php
tests/Unit/CLI/Printer/TextPrinterTest.php

Introduced the "gitlab" format for CLI output, alongside existing "text" and "json" formats. This includes a new `GitlabPrinter` implementation, updates to the `PrinterFactory` and output option handling, as well as corresponding unit and E2E tests. The change enhances integration options, particularly for GitLab CI.
gitlab code quality format must have particular json format
see gitlab docs: https://docs.gitlab.com/ci/testing/code_quality/#code-quality-report-format
this PR depends on #475

feat: Add GitLab output format support to CLI.

---

README.md

Updated the README to include 'gitlab' as an available output format in addition to 'text' and 'json'. Clarified the use cases for the 'json' format and specified its compatibility with platforms like GitHub Actions and SonarQube.

README: Add support for 'gitlab' as an output format

---

src/CLI/Command/Check.php
src/CLI/Printer/TextPrinter.php
src/CLI/Runner.php
tests/E2E/Cli/CheckCommandTest.php
tests/E2E/Smoke/RunArkitectBinTest.php
tests/Unit/CLI/Printer/TextPrinterTest.php
tests/Unit/Rules/ViolationsTest.php

Here the output is divided between STDOUT and STDERR, in particular:
- the list of violations is printed on stdout
- everything else on stderr
This has several benefits
- we can remove the `$onlyError` logic scattered in the code
- the output now can be piped to other commands or in a file and in case of json/gitlab format you end up having a valid json

Print violations to stdout, everything else to stderr

---

src/CLI/Baseline.php
src/CLI/Command/Check.php
src/CLI/Config.php
src/CLI/ConfigBuilder.php
src/CLI/Printer/PrinterFactory.php
src/CLI/Runner.php
src/CLI/TargetPhpVersion.php
src/PHPUnit/ArchRuleCheckerConstraintAdapter.php
src/Rules/Violations.php
tests/Unit/CLI/Printer/PrinterFactoryTest.php
tests/Unit/Rules/RuleCheckerTest.php
tests/Unit/Rules/ViolationsTest.php

Introduce a ConfigBuilder and moves several params into the Config class. With that, 
- the Runner class has more information about the input params. and can make potentially more decision on how to run the analisys
- it enables (still some more work is needed) to specify the input params also in the phparkitect.php config file and having the command line option overriding those values

Use Config class to collect several configurations

---

bin-stub/phparkitect

I am not sure about this one, the different includes seems redundant, without this code the CI is green...
Any additional test we can make to check if this is useful?

simplify init

---

README.md
src/CLI/Command/Check.php
src/CLI/Config.php
tests/E2E/Cli/CheckCommandTest.php
tests/E2E/_fixtures/autoload/autoload.php
tests/E2E/_fixtures/autoload/phparkitect.php
tests/E2E/_fixtures/autoload/src/Model/User.php
tests/E2E/_fixtures/autoload/src/Model/UserInterface.php
tests/E2E/_fixtures/autoload/src/Service/UserService.php
tests/Unit/CLI/Printer/GitlabPrinterTest.php

**Context:** as we are considering the possibility to use functions like `is_a` in the rules, we need a way to deal with the autoload of the classes phparkitect is analizyng
We have two scenarios based on how phparkitect is installed
**as a project dependency via composer:** this is the simplest case since, since phparkitect shares the autoload with the project it analyzes, no additional autoloader is needed ✅ 
**as a phar:** here phparkitect autoload is embedded in the phar itself, so we need a way to autoload the project's classes
In the second scenario, we should consider the phar could be in different locations: 
- global, like in `/usr/local/bin/phparkitect`
- in the project root
- in the project `bin` dir
- ...
so trying to guess where the project autoload could be can be …

Check: adds an option to specifiy an autoloader file to be included

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileParser/CanParseClassTest.php

This will fix #498. A small improved was also added: anonymous classes `extends` is now collected as dependency

split FileVisitor::handleClassNode into handleClassNode and handleAnonClassNode

---

src/Analyzer/DocblockTypesResolver.php
tests/Unit/Analyzer/DocblockParserTest.php
tests/Unit/Analyzer/DocblockTypesResolverTest.php

This should fix #509. The updated implementation ignores any type defined in docblock which is not a class fqcn
NB: support for union types is still missing we are going to tackle it in separate PR(s)

Ignore union types in dockblock definitions

---

Makefile
src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileParser/CanParseClassPropertiesTest.php
tests/Unit/Analyzer/FileParser/CanParseClassTest.php

some more refactorings before tackling the @throws tag dependency collection 
1. refactored to avoid nested conditionals
2. preferred checks like `$node->class instanceof Node\Name\FullyQualified` instead of `method_exists($node->class, 'toString')`. This allows to skip checks on parent:: self:: static:: and native types since a `Node\Name\FullyQualified` refers always to a class

FileVisitor improvements
