phparkitect/arkitect

composer.json
composer.lock

Support multiple Symfony versions

---

src/Analyzer/ClassDependency.php
tests/Unit/Analyzer/ClassDependencyTest.php

fixed matches one of inside ClassDependency changing logic

---

bin-stub/phparkitect
src/CLI/Application.php

Adds ascii art logo and version

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

What do you think @micheleorselli about the test in this PR?
I used an old test, but I would like to know if you would expect a specific test for this new feature.

added static dependencies

---

.php-cs-fixer.dist.php
src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileParser.php
src/Analyzer/FileVisitor.php
src/Expression/ForClasses/Extend.php
tests/Unit/Analyzer/FileVisitorTest.php
tests/Unit/Expressions/ForClasses/ExtendTest.php
tests/Unit/Expressions/ForClasses/ImplementConstraintTest.php
tests/Unit/Expressions/ForClasses/NotHaveDependencyOutsideNamespaceTest.php

Adds extend rule

---

src/CLI/Version.php

fixed get version when phparkitect is installed via composer

---

tests/Unit/CLI/Progress/DebugProgressTest.php
tests/Unit/Rules/ParsingErrorsTest.php

Added tests for `DebugProgress` class and `ParsingErrors` class

added tests

---

README.md
tests/Unit/CLI/VersionTest.php

Solve the issue: https://github.com/phparkitect/arkitect/issues/183

docs: remove Docker usage from README.md

---

tests/E2E/Cli/CheckCommandTest.php

refactoring of CheckCommandTest (Don't Repeat Yourself)

update CheckCommandTest (dry)

---

Makefile
bin-stub/phparkitect
box.json
phparkitect-stub.php
src/CLI/Command/Init.php
tests/E2E/Cli/InitCommandTest.php
tests/Unit/CLI/VersionTest.php

Adds init command

---

psalm.xml
src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

avoid adding dependencies if class description builder is null

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

removed self as a dependency if it s found

---

README.md
src/Analyzer/ClassDescription.php
src/Rules/AllClasses.php
src/Rules/ArchRule.php
src/Rules/DSL/ThatParser.php
src/Rules/RuleBuilder.php
tests/E2E/Cli/phparkitect.php
tests/E2E/Smoke/phparkitect.php
tests/E2E/_fixtures/configMvc.php
tests/E2E/_fixtures/configMvcForYieldBug.php
tests/E2E/_fixtures/configMvcWithoutErrors.php
tests/E2E/_fixtures/mvc/Controller/BaseController.php
tests/E2E/_fixtures/mvc/Services/Foo/Bar.php
tests/Unit/Analyzer/ClassDescriptionTest.php

In this PR I added the possibility to exclude classes when we parse the codebase.
This is one of the different steps for this issue #209

Added exclude function dsl

---

composer.json

Tested on my project with php 8.1 and Symfony 6.0 on theses components, I got no problem.

Allow Symfony 6.x

---

src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileVisitor.php
src/Expression/ForClasses/IsFinal.php
src/Expression/ForClasses/IsNotFinal.php
tests/Unit/Analyzer/ClassDescriptionBuilderTest.php
tests/Unit/Expressions/ForClasses/ExtendTest.php
tests/Unit/Expressions/ForClasses/ImplementTest.php
tests/Unit/Expressions/ForClasses/IsFinalTest.php
tests/Unit/Expressions/ForClasses/IsNotFinalTest.php
tests/Unit/Expressions/ForClasses/NotExtendTest.php
tests/Unit/Expressions/ForClasses/NotHaveDependencyOutsideNamespaceTest.php
tests/Unit/Expressions/ForClasses/NotImplementTest.php

In this PR I added the rule to validate if a class isFinal or notIsFinal.
I get the information inside the FileVisitor with the specific method offered by the Parser.
Refer to issue: #240

added isFinal and isNotFinal rule

---

src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileVisitor.php
src/Expression/ForClasses/IsAbstract.php
src/Expression/ForClasses/IsNotAbstract.php
tests/Unit/Analyzer/ClassDescriptionBuilderTest.php
tests/Unit/Expressions/ForClasses/ExtendTest.php
tests/Unit/Expressions/ForClasses/ImplementTest.php
tests/Unit/Expressions/ForClasses/IsAbstractTest.php
tests/Unit/Expressions/ForClasses/IsFinalTest.php
tests/Unit/Expressions/ForClasses/IsNotAbstractTest.php
tests/Unit/Expressions/ForClasses/NotExtendTest.php
tests/Unit/Expressions/ForClasses/NotHaveDependencyOutsideNamespaceTest.php
tests/Unit/Expressions/ForClasses/NotImplementTest.php

In this PR I added `isAbstract` and `isNotAbstract` rules
Related to #243

added asbtract and not abstract rules

---

.github/workflows/update-contributors.yml
CONTRIBUTORS.md

In this PR I added the contributors file empty voluntarily to test the workflow.
The new workflow runs every Sunday at 12:00 pm and it should update the file automatically.

added contributors file and workflow to update file automatically

---

.github/workflows/build.yml

@AlessandroMinoccheri this should fix the composer issue

tries to fix composer issues

---

README.md
src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileVisitor.php
src/Expression/ForClasses/DocBlockContains.php
tests/Unit/Analyzer/ClassDescriptionBuilderTest.php
tests/Unit/Analyzer/ClassDescriptionTest.php

adding HaveAnnotation rule

---

README.md
src/CLI/Check.php
src/CLI/Runner.php
src/Exceptions/FailOnFirstViolationException.php
src/Rules/Violations.php
tests/E2E/Cli/CheckCommandTest.php

adds stop on failure option using exceptions

---

README.md

This PR should solve #254 
I removed the list of rules with specific examples.
We should add a description for each rule? Or is it clear?

Adding specific examples for each rule

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

fixed self static and parent for class static

---

bin-stub/phparkitect
composer.json
src/CLI/PhpArkitectApplication.php
tests/E2E/Cli/CheckCommandTest.php
tests/E2E/Cli/InitCommandTest.php

Now our end to end tests are a little bit more end to end... Instead of testing the single command we test the application.

use ApplicationTester instead of CommandTester for E2E

---

.editorconfig

added file editorconfig to avoid different IDE styles

---

src/CLI/Command/Check.php

I have added the execution time at the end of the script execution like this:

print execution time when the script finish to run

---

src/Analyzer/FileVisitor.php
tests/E2E/_fixtures/mvc/Services/CartService.php
tests/E2E/_fixtures/mvc/Services/Foo/Bar.php
tests/Unit/Analyzer/FileVisitorTest.php

This PR solves the third problem of issue #307 about typed properties.
Now we can parse Property directly

added check dependencies for properties

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

added a try catch to avoid errors on parsing docblocks

---

.github/workflows/build.yml
README.md
src/CLI/TargetPhpVersion.php

This PR cannot pass the CI architectural rules step because it takes the last version from GitHub actions.
So we can merge it if it's ok.

added php 8.2 into ci and support it

---

src/Analyzer/NameResolver.php
tests/Unit/Analyzer/FileVisitorTest.php

In this PR the code can parse custom tags in property docblocks.

Parse custom tags

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

This PR solves this issue: #339

considering array type as a scalar type

---

src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileParserFactory.php
src/Analyzer/FullyQualifiedClassName.php
src/Analyzer/PatternString.php
tests/Unit/Analyzer/ClassDescriptionBuilderTest.php
tests/Unit/Analyzer/ClassDescriptionTest.php
tests/Unit/Analyzer/FullyQualifiedClassNameTest.php
tests/Unit/Analyzer/PatternStringTest.php
tests/Unit/Rules/ConstraintsTest.php

I refactored some code when I started working on #330, but I think this deseverves a PR on his own.

Dead code removed and minor refactorings

---

src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileVisitor.php
src/Expression/ForClasses/Implement.php
src/Expression/ForClasses/NotImplement.php
tests/Unit/Analyzer/ClassDescriptionBuilderTest.php
tests/Unit/Analyzer/FileVisitorTest.php
tests/Unit/Expressions/ForClasses/ContainDocBlockLikeTest.php
tests/Unit/Expressions/ForClasses/ExtendTest.php
tests/Unit/Expressions/ForClasses/HaveAttributeTest.php
tests/Unit/Expressions/ForClasses/ImplementTest.php
tests/Unit/Expressions/ForClasses/IsAbstractTest.php
tests/Unit/Expressions/ForClasses/IsFinalTest.php
tests/Unit/Expressions/ForClasses/IsNotAbstractTest.php
tests/Unit/Expressions/ForClasses/IsNotFinalTest.php
tests/Unit/Expressions/ForClasses/NotContainDocBlockLikeTest.php
tests/Unit/Expressions/ForClasses/NotExtendTest.php
tests/Unit/Expressions/ForClasses/NotHaveDependencyOutsideNamespaceTest.php
tests/Unit/Expressions/ForClasses/NotImplementTest.php

parsing trait also

---

src/Expression/ForClasses/MatchOneOfTheseNames.php
tests/Unit/Expressions/ForClasses/MatchOneOfTheseNamesTest.php

Implement MatchOneOfTheseNames

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

parsing nullable properties correctly

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

Parsing optional parameter

---

tests/Unit/Analyzer/FileVisitorTest.php

Fix indentation in FileVisitorTest

---

composer.json
src/CLI/Command/Check.php
src/CLI/Progress/ProgressBarProgress.php

don't show progress bar on CI

---

.php-cs-fixer.dist.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileVisitor.php
src/Analyzer/NameResolver.php
src/Analyzer/PatternString.php
src/Expression/ForClasses/DependsOnlyOnTheseNamespaces.php
src/Rules/Violation.php
tests/E2E/Cli/CheckCommandTest.php

This was the origin of the problem:
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6987

Fix cs fixer bug on ci

---

src/RuleBuilders/Architecture/MayDependOnComponents.php
src/RuleBuilders/Architecture/ShouldOnlyDependOnComponents.php

To improve understanding of mayDependOnComponents
and shouldOnlyDependOnComponents

Add doc-blocks

---

src/Expression/ForClasses/ResideInOneOfTheseNamespaces.php
tests/Unit/Expressions/ForClasses/ResideInOneOfTheseNamespacesTest.php

Prevent duplicate namespaces in ResideInOneOfTheseNamespaces

---

src/ClassSet.php
tests/Integration/CheckEnumTest.php

This is a test to verify the behaviour reported in #429

Adds a test to check for a potential bug on enums check

---

src/Analyzer/FileVisitor.php
tests/Unit/Analyzer/FileVisitorTest.php

I wrongly reverted a change proposed in #444, so here I am fixing it. 
This approach, apart for requiring less code, is more robust as it takes into consideration all attributes, being them attached to a class, method, etc etc

Improves parsing of attributes

---

src/Analyzer/ClassDescription.php
src/Analyzer/ClassDescriptionBuilder.php
src/Analyzer/FileVisitor.php
src/Expression/ForClasses/Extend.php
src/Expression/ForClasses/NotExtend.php
tests/Unit/Analyzer/FileVisitorTest.php
tests/Unit/Expressions/ForClasses/ExtendTest.php
tests/Unit/Expressions/ForClasses/NotExtendTest.php
tests/Unit/Expressions/ForClasses/NotImplementTest.php

This should implement #458. Since interfaces can extend multiple interfaces 🤯 the extend property is now an array

Collect extends also for interfaces

---

src/CLI/Command/Check.php
src/CLI/Runner.php

Imo the Runner class should know if and when to stop the analysis

Moves catch FailOnFirstViolationException in the Runner class
